### ISSUE TITLE
Serverless Resource creation

### ISSUE THREAD

**Issue by DishenWang2023** [thiskevinwang/terraform-provider-pinecone#13]
Hello, since pinecone introduced their new serverless solution for vector database, is it possible to update this provider such that we can create serverless index with terraform?

**Comment by thiskevinwang** [comment]
Hey @DishenWang2023 - the [docs](https://docs.pinecone.io/docs/create-an-index#create-a-serverless-index) say the serverless indices are still in preview, with very strict limitations (Cloud and Region).

<img width="819" alt="CleanShot 2024-03-02 at 12 35 05@2x" src="https://github.com/thiskevinwang/terraform-provider-pinecone/assets/26389321/0e888983-1ec1-4c81-ab0b-da509660221b">

As long as it's in preview, I personally won't add it, but PRs are more than welcome! :)
